### ISSUE TITLE
senzing-mysql-init service fails if Senzing is installed to somewhere other than /opt/senzing

### ISSUE THREAD

**Issue by jeffadair** [Senzing/docker-compose-stream-loader-kafka-demo#5]
**Describe the bug**
When when Senzing is installed to somewhere other than /opt/senzing and docker-compose-stream-loader-kafka-demo.yaml is brought up, the senzing-mysql-init service will fail with the following output:

```
senzing-mysql-init | ERROR at line 1: Failed to open file '/opt/senzing/g2/data/g2core-schema-mysql-create.sql', error: 2
senzing-mysql-init | Sleeping 15 seconds, then will re-try.

```
As you can see, it is using the default location for senzing.

**To Reproduce**
Install Senzing to a non default location, set the SENZING_DIR environment variable to the installed location, and then bring up docker-compose-stream-loader-kafka-demo.yaml as instructed. Watch for  senzing-mysql-init output.

**Expected behavior**
Execute successfully and exit with code zero

`senzing-mysql-init exited with code 0`

**Screenshots**

**Desktop (please complete the following information):**

- OS: CentOS

**Comment by docktermj** [comment]
Pull Request:
- https://github.com/Senzing/docker-compose-stream-loader-kafka-demo/pull/6
